package com.acaboumony.user.security;

import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.regex.Pattern;

/**
 * Utility for decoding base64-encoded PEM keys (with or without PEM headers/footers).
 *
 * <p>Accepts keys in two formats:</p>
 * <ol>
 *   <li>Raw base64 (no headers) — as stored in {@code application.yml} for dev/test.</li>
 *   <li>PEM with {@code -----BEGIN ... KEY-----} / {@code -----END ... KEY-----} headers and
 *       embedded {@code \n} line breaks — as generated by {@code openssl}.</li>
 * </ol>
 */
public final class RsaKeyLoader {

    private static final Pattern HEADER_PATTERN =
            Pattern.compile("-----[A-Z ]+-----");

    private RsaKeyLoader() {}

    /**
     * Loads a {@link PrivateKey} from a base64-encoded PKCS#8 DER string.
     *
     * @param base64Pem raw base64 or PEM-formatted string
     * @return decoded {@link PrivateKey}
     */
    public static PrivateKey loadPrivateKey(String base64Pem) {
        try {
            byte[] decoded = decode(base64Pem);
            PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(decoded);
            return KeyFactory.getInstance("RSA").generatePrivate(spec);
        } catch (Exception e) {
            throw new IllegalArgumentException("Failed to load RSA private key", e);
        }
    }

    /**
     * Loads a {@link PublicKey} from a base64-encoded X.509 DER string.
     *
     * @param base64Pem raw base64 or PEM-formatted string
     * @return decoded {@link PublicKey}
     */
    public static PublicKey loadPublicKey(String base64Pem) {
        try {
            byte[] decoded = decode(base64Pem);
            X509EncodedKeySpec spec = new X509EncodedKeySpec(decoded);
            return KeyFactory.getInstance("RSA").generatePublic(spec);
        } catch (Exception e) {
            throw new IllegalArgumentException("Failed to load RSA public key", e);
        }
    }

    private static byte[] decode(String base64Pem) {
        // Strip PEM headers/footers and whitespace, then base64-decode
        String clean = HEADER_PATTERN.matcher(base64Pem).replaceAll("");
        clean = clean.replaceAll("\\s+", "");
        return Base64.getDecoder().decode(clean);
    }
}
